name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps
        run: pnpm i

      # Runs a set of commands using the runners shell
      - name: Build and Test
        run: pnpm test
